### ISSUE TITLE
Competitor Branding Visual Research

### ISSUE THREAD

**Issue by ghost** [foundersandcoders/assets#10]
Mark and Noga to conduct visual research into competitor branding

**Mark**
Bootcamps (hacker school, app academy, Makers, GA, Ecole 42)
Accelerators
Incubators
Social Enterprise Agencies

**Noga**
Tech for Good Companies
Cooperatives
Spiced Academy
Codebar
Online Platforms (Free code camp, Codecademy, Codewars)
BA in Web development (Paris)

Branding folder is here: https://drive.google.com/drive/folders/0BzAAKt4fbFbgVkYtbUY2VnZuc2s

Document to put research into is here: https://docs.google.com/presentation/d/12RlRKNtT7WGjEpe-hsqPFpki5DRW3GtrjceqRhWftUQ/edit?usp=sharing

**Comment by markwilliamfirth** [comment]
@NataliaLKB @nogainbar 

Another lightbulb-plant logo to do with clean energy popped up in my inbox today
<img width="601" alt="screen shot 2017-05-10 at 13 49 25" src="https://cloud.githubusercontent.com/assets/5732209/25899403/9c171488-3587-11e7-8376-72356fc1603b.png">
