### ISSUE TITLE
Organise Ideation Session

### ISSUE THREAD

**Issue by markwilliamfirth** [foundersandcoders/assets#11]
Mark to organise branding ideation session with Mark, @nogainbar and @NataliaLKB .

One evening in 2-3 weeks time, after visual research has been completed

**Comment by nogainbar** [comment]
@markwilliamfirth @NataliaLKB shall we book a date for this ideation session? wanted to also add @andrewMacmurray coz he is so awesome. :)

**Comment by markwilliamfirth** [comment]
@nogainbar @NataliaLKB @andrewMacmurray 

How does 2 May or 8 May sound?

**Comment by NataliaLKB** [comment]
May 2nd is Ladies of Code so I can't make it. I could do the 8th though!

**Comment by markwilliamfirth** [comment]
@nogainbar @andrewMacmurray May 8th?

**Comment by nogainbar** [comment]
Yup, sound good to me! @markwilliamfirth
What time would suit everyone?

**Comment by andrewMacmurray** [comment]
@markwilliamfirth yep that works for me

**Comment by markwilliamfirth** [comment]
Woohooooo

Ok

14 Palmers Rd
8th May 2017
6:30 PM - 7:30 PM

I've sent you all calendar invitations!  🎉
