### ISSUE TITLE
Upload FAC 11 Pictures 

### ISSUE THREAD

**Issue by y-zaky** [foundersandcoders/assets#15]
Hi @sohilpandya ,

Could you kindly upload the FAC 11 Pictures ! We would like to use them for marketing purposes !

Many thanks 👍

**Comment by rebeccaradding** [comment]
@sohilpandya mind uploading those photos to https://drive.google.com/drive/folders/0B-mliovLR9b_X3lsR3BzcmJ0Znc?usp=sharing instead? Thanks!

**Comment by sohilpandya** [comment]
Done. Finally! 

Apologies for the delay. 👍
