### ISSUE TITLE
Logo version history usage dates

### ISSUE THREAD

**Issue by ghost** [foundersandcoders/assets#8]
Dan to calculate timeline of usage of versions of the logo. Dates from when various versions have been used until now.

**Comment by sofer** [comment]
+ selforganising logo: Nov 2012 https://github.com/selforganising/selforganising/blob/gh-pages/images/self.png
+ Founders & Coders logo (take 1): June 2014 https://github.com/selforganising/foundersandcoders/blob/gh-pages/images/icon.png: 
+ Founders & Coders logo (take 2): November 2014? https://github.com/foundersandcoders/assets/blob/master/brand/logo.png
