### ISSUE TITLE
Create Current Brand Guidelines

### ISSUE THREAD

**Issue by ghost** [foundersandcoders/assets#9]
Noga to create current brand guidelines, including:

Logo
Logo text
Logo text font family
Colour palette
Website font family

**Comment by nogainbar** [comment]
see [document](https://drive.google.com/open?id=0B24Sdkg-P6Mna0t3UXNGdUc4N3M) on google drive

**Comment by markwilliamfirth** [comment]
@nogainbar it appears that the logo at the top of the page of the guideline is different to the logo suggested in the guideline

**Comment by markwilliamfirth** [comment]
@nogainbar can we update these and then we can give them to sohil to order the tshirts?

@NataliaLKB who was the person who has contact with the original designer with the original file?

**Comment by iteles** [comment]
@markwilliamfirth Pretty sure it was @NataliaLKB who designed the original lightbulb logo ;)

**Comment by markwilliamfirth** [comment]
@iteles referencing the tshirt design file

**Comment by NataliaLKB** [comment]
@markwilliamfirth for the t-shirt designer I don't know who they are. @adamdiy was the one in contact with them. The t-shirts were always just meant for the indigogo campaign.

**Comment by markwilliamfirth** [comment]
@adamdiy do you have the design file or know the email address of the designer who made these tshirts for the indiegogo campaign:
<img width="276" alt="screen shot 2017-05-09 at 15 11 01" src="https://cloud.githubusercontent.com/assets/5732209/25854984/c6f25f0a-34c9-11e7-8ca5-a24fbd7c09ff.png">

I don't mind chasing them to try and find the design files!

**Comment by markwilliamfirth** [comment]
@adamdiy not sure if you saw this, but figured I'd try tagging again! You don't by any chance have the email address of the designer for the t-shirts somewhere in your email history?

**Comment by markwilliamfirth** [comment]
Tshirts were designed by Sophie Alda sophiealda (at) icloud.com

![fandc shirt mock](https://user-images.githubusercontent.com/5732209/28716898-7bae9aba-7397-11e7-814c-61e61bd16385.jpg)

![codey shirt](https://user-images.githubusercontent.com/5732209/28716902-8708c660-7397-11e7-9fc6-82793909fb8e.jpg)

![img_4321](https://user-images.githubusercontent.com/5732209/28716943-ae1bb3d4-7397-11e7-8482-7441c1833bb1.JPG)
![img_4319](https://user-images.githubusercontent.com/5732209/28716944-ae1c8a3e-7397-11e7-8ba7-86c9a6796bd2.JPG)
![img_4317](https://user-images.githubusercontent.com/5732209/28716945-ae219614-7397-11e7-939d-6289f6ee9650.JPG)
![img_4313](https://user-images.githubusercontent.com/5732209/28716946-ae24ec7e-7397-11e7-8070-b774e25ef1a7.JPG)


They were printed by a friend of @adamdiy called Christopher Murphy info (at) thepositivepress.co.uk

Print office address:
Print Club London
Unit 3, 10-28 Millers Ave. 
e8 2DS
